name: Test

on: [push, pull_request]

jobs:

  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.11' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: ${{ matrix.python-version == '3.11' }}
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install legacy Poetry for Python 3.6
        uses: snok/install-poetry@v1
        if: ${{ matrix.python-version  == '3.6' }}
        with:
          version: 1.1.14
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Regenerate Poetry lock for Python 3.6
        if: ${{ matrix.python-version  == '3.6' }}
        run: |
          rm poetry.lock
          poetry lock

      - name: Load cached Poetry virtualenv
        uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: |
          poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Tests and produce coverage
        continue-on-error: true
        run: |
          poetry run coverage run -m unittest discover
          poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: runner.python-version == '3.6' && github.event_name != 'pull_request'
        with:
          file: coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
